version: '3.8'
services:
  api_scheduler:
    build: .
    container_name: poli_reserbak_api
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./db:/app/db
      - crontab_data:/var/spool/cron/crontabs

volumes:
  crontab_data:
    driver: local